### ISSUE TITLE
Your WebUSB util seems don't act on V2.21 Board

### ISSUE THREAD

**Issue by dongjoon9331** [bsiever/microbit-webusb#4]
Hi?
Thank you for distributing the WebUSB Utility.
However, it seems that a communication error occurs on a specific board.
Please refer to the photo below.
Could you please fix this communication error?

v1 board
![v1](https://user-images.githubusercontent.com/75997501/199473593-c4f671c3-66e4-437b-83e4-1e5fc006578b.png)

v2.00 board
![v2 0](https://user-images.githubusercontent.com/75997501/199473628-010d7871-f969-4903-be48-962450fbe764.png)

v2.21 board
![v2 21](https://user-images.githubusercontent.com/75997501/199473658-5ba066f3-a706-45a4-8895-9b3f755bcc03.png)

**Comment by bsiever** [comment]
I just got a v2.21 on Thursday.  I will look into this problem soon.

**Comment by bsiever** [comment]
@dongjoon9331  Sorry for the delay.  I've updated it to rely on [Dap.js](https://github.com/ARMmbed/dapjs) and it seems to \ work with all three major micro:bit releases (1.5, 2.0, 2.21).  See https://github.com/bsiever/microbit-webusb/releases/tag/v1.0.0 .
