### ISSUE TITLE
serial.writeValue() breaks connection

### ISSUE THREAD

**Issue by CaptainCredible** [bsiever/microbit-webusb#6]
Hi! its been a year and something is broken again. I cant tell where the issue is (microbit or chrome) but sending a serial.writeValue("x", 123) causes the microbit to disconnect. Sending basig strings using e.g. serial.writeLine() works fine however. in some situations the disconnect is accompanied by the error :   "Bad response for 8 -> 17" as in your examples:
![Screenshot 2024-09-09 at 17 58 28](https://github.com/user-attachments/assets/aeb6606b-95d8-46b1-8719-9ea9bc9d5f99)

Hope this is an easy fix as I hope to use this in teaching a university course this friday. 

Finger crossed!

**Comment by CaptainCredible** [comment]
Wait a minute, i think this might be an error in my code...

**Comment by CaptainCredible** [comment]
Yes sorry, things seem to be working now. ignore what i said.

**Comment by bsiever** [comment]
I'm glad you were able to resolve it!
